#!/bin/bash
echo "----------------------------------------"
echo "All in One Animation Control..."
cd frameworks/base
echo "[1/3] Base: https://gerrit.omnirom.org/4251"
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/51/4251/39 && git cherry-pick FETCH_HEAD
cd  ../..
echo "----------------------------------------"
cd packages/apps/Settings
echo "[2/3] Settings: https://gerrit.omnirom.org/4250"
git fetch https://gerrit.omnirom.org/android_packages_apps_Settings refs/changes/50/4250/15 && git cherry-pick FETCH_HEAD
cd ..
echo "----------------------------------------"
cd OmniGears
echo "[3/3] OmniGears: https://gerrit.omnirom.org/4249"
git fetch https://gerrit.omnirom.org/android_packages_apps_OmniGears refs/changes/49/4249/35 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "DONE"
