#!/bin/bash
echo "----------------------------------------"
cd frameworks/base
echo "----------------------------------------"
echo "[1/3] frameworks/base: add "Accept all files" option for incoming files via Bluetooth https://gerrit.slimroms.net/#/c/13477/"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_base refs/changes/77/13477/4 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
cd packages/apps/Settings
echo "[2/3] Settings: add "Accept all files" option for incoming files via Bluetooth https://gerrit.slimroms.net/#/c/21452/"
git fetch https://gerrit.slimroms.net/SlimRoms/packages_apps_Settings refs/changes/52/21452/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/apps/Bluetooth
echo "[3/3] Bluetooth: add "Accept all files" option for incoming files via Bluetooth https://gerrit.slimroms.net/#/c/21451/"
git fetch https://gerrit.slimroms.net/SlimRoms/packages_apps_Bluetooth refs/changes/51/21451/2 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "DONE"
