#!/bin/bash
echo ""
echo "----------------------------------------"
cd frameworks/base
echo "[1/3]frameworks/base: add <Accept all files> option for incoming files via Bluetooth"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_base refs/changes/85/21885/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
cd packages/apps/Bluetooth
echo "[2/3]Bluetooth: add <Accept all files> option for incoming files via Bluetooth"
git fetch https://gerrit.slimroms.net/SlimRoms/packages_apps_Bluetooth refs/changes/23/24123/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd packages/apps/Settings
echo "[3/3]Settings: add <Accept all files> option for incoming files via Bluetooth"
git fetch https://gerrit.slimroms.net/SlimRoms/packages_apps_Settings refs/changes/22/24122/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
echo "Done!"
echo "----------------------------------------"
echo "----------------------------------------"
