#!/bin/bash
# Your build source code directory path. In the example below the build source code directory path is in the "home" folder. If your source code directory is on an external HDD it should look like: //media/your PC username/the name of your storage device/path/to/your/source/code/folder
SAUCE=~/android/cm-13.0

# Let's apply all commits!
echo ""
echo "----------------------------------------"
cd $SAUCE/device/samsung/p3100
echo "----------------------------------------"
echo "nothing for now"
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/device/samsung/p3110
echo "----------------------------------------"
echo "nothing for now"
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/device/samsung/p5100
echo "----------------------------------------"
echo "nothing for now"
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/device/samsung/p5110
echo "----------------------------------------"
echo "nothing for now"
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/device/samsung/espresso-common
echo "----------------------------------------"
echo "nothing for now"
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
cd $SAUCE/kernel/samsung/espresso10
echo "----------------------------------------"
git fetch http://review.cyanogenmod.org/CyanogenMod/android_kernel_samsung_espresso10 refs/changes/32/133732/3 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/vendor/samsung
echo "----------------------------------------"
git fetch https://github.com/andi34/proprietary_vendor_samsung-1.git cm-13.0
git cherry-pick dc4529660342f65d4c9968c4f05913eb0bb88d61
git cherry-pick 132ee94600d846625f16ad5bad0ddd1085d5daab
echo "----------------------------------------"
echo "----------------------------------------"
echo "Done!"
cd $SAUCE
echo "----------------------------------------"
echo "----------------------------------------"
