#!/bin/bash
echo ""
echo "Picking latest translations..."
echo "----------------------------------------"
cd frameworks/base
git fetch https://review.slimroms.eu/SlimRoms/frameworks_base refs/changes/93/3393/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
cd packages/apps/Camera2
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_Camera2 refs/changes/94/3394/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/apps/Settings
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_Settings refs/changes/95/3395/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/apps/SlimLauncher
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_SlimLauncher refs/changes/96/3396/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/providers/MediaProvider
echo "nothing"
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/providers/DownloadProvider
git fetch https://review.slimroms.eu/SlimRoms/packages_providers_DownloadProvider refs/changes/97/3397/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "Done!"
echo "Latest translations cherry-picked!"

