#!/bin/bash
echo ""
echo " S L I M R O M S   C R O W D I N  -  T R A N S L A T I O N"
echo "Picking latest translations..."
echo "----------------------------------------"
cd frameworks/base
git fetch https://review.slimroms.eu/SlimRoms/frameworks_base refs/changes/20/6620/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
cd packages/apps/Camera2
echo "nothing"
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd packages/apps/Dialer
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_Dialer refs/changes/21/6621/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd packages/apps/InCallUI
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_InCallUI refs/changes/22/6622/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd packages/apps/Mms
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_Mms refs/changes/23/6623/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/apps/Settings
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_Settings refs/changes/24/6624/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/apps/SlimLauncher
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_SlimLauncher refs/changes/25/6625/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/services/Telecomm
git fetch https://review.slimroms.eu/SlimRoms/packages_services_Telecomm refs/changes/26/6626/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/providers/MediaProvider
echo "nothing"
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd packages/providers/DownloadProvider
echo "nothing"
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "Done!"
echo "Latest translations cherry-picked!"

