#!/bin/bash
cd system/vold
echo "----------------------------------------"
echo "Add exfat/ntfs support for modules or static mode. http://review.cyanogenmod.org/62307"
git fetch http://review.cyanogenmod.org/CyanogenMod/android_system_vold refs/changes/07/62307/14 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
echo "Ext4: SD card write access workaround"
git fetch https://github.com/kumajaya/android_system_vold.git cm-11.0 && git cherry-pick bd795445b6e4f0ed2aeebfa0c2ed25fe21000ae9
echo "----------------------------------------"
cd ../..
cd external/busybox
echo "Always enable reboot applet"
git fetch https://github.com/kumajaya/android_external_busybox.git && git cherry-pick 6d2ed7af6d472c8dd7a850fa229895573bbb8e4d
echo "----------------------------------------"
cd ../..
cd build
echo "LZMA compressed recovery"
git fetch https://github.com/kumajaya/android_build
git cherry-pick e4861629ccb05e88a83ca976a6073596d253448d
echo "----------------------------------------"
cd ..
echo "Done!"
