#!/bin/bash
echo ""
echo " S A M S U N G  G A L A X Y  T A B  2"
echo "       F 2 F S  S u p p o r t        "
echo ""
echo "https://review.slimroms.eu/#/q/status:open+branch:lp5.1+topic:espresso10-f2fs"
echo "----------------------------------------"
cd device/samsung/p3100
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/device_samsung_p3100 refs/changes/90/6690/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/device_samsung_p3100 refs/changes/91/6691/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd device/samsung/p3110
echo "Nothing to do..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd device/samsung/p5100
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/device_samsung_p5100 refs/changes/92/6692/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/device_samsung_p5100 refs/changes/93/6693/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd device/samsung/p5110
echo "Nothing to do..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo ""
cd device/samsung/omap4-common
echo "----------------------------------------"
echo "Nothing to do..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
echo "----------------------------------------"
echo "----------------------------------------"
cd kernel/samsung/espresso10
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/68/6668/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/69/6669/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/70/6670/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/71/6671/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/72/6672/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/73/6673/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/74/6674/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/75/6675/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/76/6676/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/77/6677/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/78/6678/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/79/6679/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/80/6680/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/81/6681/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/82/6682/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/83/6683/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/84/6684/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/85/6685/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/86/6686/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/87/6687/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/kernel_samsung_espresso10 refs/changes/89/6689/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
echo "Done!"
echo "----------------------------------------"
echo "----------------------------------------"
