#!/bin/bash
echo ""
echo "----------------------------------------"
cd device/samsung/p3100
echo "P31XX: ffmpeg codec support https://gerrit.slimroms.net/#/c/24382/"
git fetch https://gerrit.slimroms.net/SlimRoms/device_samsung_p3100 refs/changes/82/24382/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd device/samsung/p3110
echo "Nothing to do..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd device/samsung/p5100
echo "P51XX: ffmpeg codec support https://gerrit.slimroms.net/#/c/24383/"
git fetch https://gerrit.slimroms.net/SlimRoms/device_samsung_p5100 refs/changes/83/24383/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd device/samsung/p5110
echo "Nothing to do..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo ""
echo "----------------------------------------"
echo "----------------------------------------"
cd frameworks/av
echo "ffmpeg related av commits..."
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/94/21694/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/95/21695/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/96/21696/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/97/21697/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/98/21698/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/99/21699/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/00/21700/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/01/21701/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/02/21702/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/12/24312/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/13/24313/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/14/24314/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/03/21703/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/15/24315/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/16/24316/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/17/24317/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/18/24318/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/19/24319/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/20/24320/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/21/24321/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/22/24322/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/23/24323/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/24/24324/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
cd frameworks/native
echo "Add OMX_AUDIO_CodingAPE and OMX_AUDIO_CodingDTS https://gerrit.slimroms.net/#/c/24325/"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_native refs/changes/25/24325/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
echo "omx: Add nBitsPerSample parameter for FLAC https://gerrit.slimroms.net/#/c/24326/"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_native refs/changes/26/24326/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
cd vendor/slim
echo "Remove conditions for ffmpeg https://gerrit.slimroms.net/#/c/24124/"
git fetch https://gerrit.slimroms.net/SlimRoms/vendor_slim refs/changes/24/24124/5 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
echo "Done!"
echo "----------------------------------------"
echo "----------------------------------------"

