#!/bin/bash
echo "----------------------------------------"
echo "S L I M   G L O B A L   M E N U"
echo ""
echo "https://review.slimroms.eu/#/q/topic:GlobalMenu"
echo ""
echo "----------------------------------------"
echo "----------------------------------------"
cd packages/apps/Settings
git fetch https://review.slimroms.org/SlimRoms/packages_apps_Settings refs/changes/81/681/16 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd frameworks/base
git fetch https://review.slimroms.org/SlimRoms/frameworks_base refs/changes/18/218/24 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
echo "DONE"
echo "----------------------------------------"
