#!/bin/bash
echo "----------------------------------------"
cd system/core
echo "Fix shutdown/reboot bug https://gerrit.omnirom.org/6831"
git fetch https://gerrit.omnirom.org/android_system_core refs/changes/31/6831/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
echo "init: Allow load of lpm.rc by parsing a cmdline argument"
git fetch http://review.cyanogenmod.org/CyanogenMod/android_system_core refs/changes/27/54527/1 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "DONE"
