#!/bin/bash
echo "----------------------------------------"
cd frameworks/base
echo "----------------------------------------"
echo "Lockscreen Notifications [1/2] https://gerrit.slimroms.net/12089"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_base refs/changes/89/12089/6 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
cd packages/apps/Settings
echo "Lockscreen Notifications [2/2] https://gerrit.slimroms.net/6933"
git fetch https://gerrit.slimroms.net/SlimRoms/packages_apps_Settings refs/changes/33/6933/30 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "DONE"
