#!/bin/bash

#
# NOTE: NEVER rename a *.tar.md5! Convert the recovery.img again if you want to rename the file!
#
# June 2014 Android-Andi @ XDA
# Thanks to ketut.kumajaya @ XDA
#

#---------------------Device Settings------------------#

# device name in your "out" folder
DEVICENAME1[0]="p3110"
DEVICENAME1[1]="p3100"
DEVICENAME1[2]="p5100"
DEVICENAME1[3]="p5110"
DEVICENAME1[4]="golden"

# device name for the name of the zip
DEVICENAME2[0]="GT-P3110"
DEVICENAME2[1]="GT-P3100"
DEVICENAME2[2]="GT-P5100"
DEVICENAME2[3]="GT-P5110"
DEVICENAME2[4]="GT-I8190"

#---------------------General Settings------------------#

# select "y" or "n"... Or fill in the blanks...

# recoveryname
RECNAME="TWRP"
#RECNAME="CWM"
#RECNAME="ClockworkMod-Recovery"
#RECNAME="PhilZ-Touch-Recovery"

# recovery version number
RECVER="2.7.1.0"
#RECVER="6.0.4.8"
#RECVER="6.43.8"

# move the *.tar.md5 and recovery.img?
MOVE=y

# path to move the *.tar.md5
STORAGE=~/android/roms/recovery

# Your build source code directory path.
# If your source code directory is on an external HDD it should look like: 
# //media/your PC username/the name of your storage device/path/to/your/source/code/folder
SAUCE=~/android/slimkat


#---------------------Convert & Move Code----------------#
# Very much not a good idea to change this unless you know what you are doing....

for VAL in "${!DEVICENAME1[@]}"
do

echo "Moving to out directory..."
cd $SAUCE/out/target/product/${DEVICENAME1[$VAL]}

echo "Converting..."
tar -H ustar -c recovery.img > ${DEVICENAME2[$VAL]}"_"$RECNAME"_"$RECVER".tar"
md5sum -t ${DEVICENAME2[$VAL]}"_"$RECNAME"_"$RECVER".tar" >> ${DEVICENAME2[$VAL]}"_"$RECNAME"_"$RECVER".tar"
mv ${DEVICENAME2[$VAL]}"_"$RECNAME"_"$RECVER".tar" ${DEVICENAME2[$VAL]}"_"$RECNAME"_"$RECVER".tar.md5"

if [ $MOVE = "y" ]; then
echo "moveing odin flashable *.tar.md5"
mkdir -p $STORAGE/$RECNAME
mv *".tar.md5" $STORAGE/$RECNAME/
cp "recovery.img" $STORAGE/$RECNAME/${DEVICENAME2[$VAL]}"_"$RECNAME"_"$RECVER".img"
fi

echo "Moving back to source directory..."
cd ../../../..

done

echo "Done!"
