#!/bin/bash

#
# NOTE: NEVER rename a *.tar.md5! Convert the recovery.img again if you want to rename the file!
#
# June 2014 Android-Andi @ XDA
# Thanks to ketut.kumajaya @ XDA
#


# device name in your "out" folder
DEVICENAME1="p3110"

# device name for the name of the zip
DEVICENAME2="GT-P3110"

# recoveryname
RECNAME="TWRP"

# recovery version number
RECVER="2.7.1.0"

cd out/target/product/$DEVICENAME1
tar -H ustar -c recovery.img > $DEVICENAME2"_"$RECNAME"_"$RECVER".tar"
md5sum -t $DEVICENAME2"_"$RECNAME"_"$RECVER".tar" >> $DEVICENAME2"_"$RECNAME"_"$RECVER".tar"
mv $DEVICENAME2"_"$RECNAME"_"$RECVER".tar" $DEVICENAME2"_"$RECNAME"_"$RECVER".tar.md5"
cd ../../../..
