#!/bin/bash
echo ""
echo "----------------------------------------"
cd device/samsung/p3100
echo "----------------------------------------"
echo "espresso-common: commonize bluetooth configuration"
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_p3100 refs/changes/62/109362/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p3110
echo "----------------------------------------"
echo "p3110: remove ril defines for wifi-only model"
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_p3110 refs/changes/77/109377/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p5100
echo "----------------------------------------"
echo "espresso-common: commonize bluetooth configuration"
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_p5100 refs/changes/63/109363/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p5110
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/omap4-common
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/espresso-common
echo "----------------------------------------"
echo "espresso-common: commonize bluetooth configuration"
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_espresso-common refs/changes/61/109361/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
# echo "espresso-common: Enable Dex pre-optimization"
# MIGHT BREAK XPOSED !
# git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_espresso-common refs/changes/52/106152/6 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd hardware/ti/omap4
echo "----------------------------------------"
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd kernel/samsung/espresso10
echo "----------------------------------------"
# git fetch http://review.cyanogenmod.org/CyanogenMod/android_kernel_samsung_espresso10 refs/changes/33/106133/3 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
echo "Done!"
echo "----------------------------------------"
echo "----------------------------------------"
