#!/bin/bash
echo ""
echo "----------------------------------------"
cd device/samsung/p3100
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_p3100 refs/changes/19/7719/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p3110
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_p3110 refs/changes/18/7718/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p5100
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_p5100 refs/changes/16/7716/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p5110
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_p5110 refs/changes/17/7717/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/omap4-common
echo "----------------------------------------"
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_omap4-common refs/changes/90/7690/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/espresso-common
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/82/7682/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/83/7683/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/84/7684/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/85/7685/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/86/7686/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/87/7687/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/88/7688/4 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/89/7689/3 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/20/7720/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/21/7721/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd hardware/ti/omap4
echo "----------------------------------------"
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/hardware_ti_omap4 refs/changes/91/7691/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
echo "Done!"
echo "----------------------------------------"
echo "----------------------------------------"
