#!/bin/bash
echo "----------------------------------------"
cd vendor/samsung
echo "nothing to do..."
cd ../..
echo "----------------------------------------"
cd device/samsung/p3100
echo "nothing to do..."
cd ../../..
echo "----------------------------------------"
cd device/samsung/p3110
echo "nothing to do..."
cd ../../..
echo "----------------------------------------"
cd device/samsung/p5100
echo "nothing to do..."
cd ../../..
echo "----------------------------------------"
cd device/samsung/p5110
echo "nothing to do..."
cd ../../..
echo "----------------------------------------"
cd device/samsung/espresso-common
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/98/7298/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/99/7299/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/00/7300/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/01/7301/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/02/7302/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/03/7303/1 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/device_samsung_espresso-common refs/changes/04/7304/1 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "DONE"
echo "----------------------------------------"
echo "----------------------------------------"
