#!/bin/bash
echo "----------------------------------------"
cd vendor/samsung
git cherry-pick b4cbce19f5e51b6036cbb63ab8ac27ed1a05ed13
cd ../..
echo "----------------------------------------"
cd device/samsung/p3100
echo "nothing to do..."
cd ../../..
echo "----------------------------------------"
cd device/samsung/p3110
echo "nothing to do..."
cd ../../..
echo "----------------------------------------"
cd device/samsung/p5100
echo "nothing to do..."
cd ../../..
echo "----------------------------------------"
cd device/samsung/p5110
echo "nothing to do..."
cd ../../..
echo "----------------------------------------"
cd device/samsung/espresso-common
git fetch ssh://Android-Andi@review.cyanogenmod.org:29418/CyanogenMod/android_device_samsung_espresso-common refs/changes/52/105852/1 && git cherry-pick FETCH_HEAD
git fetch ssh://Android-Andi@review.cyanogenmod.org:29418/CyanogenMod/android_device_samsung_espresso-common refs/changes/53/105853/1 && git cherry-pick FETCH_HEAD
git fetch ssh://Android-Andi@review.cyanogenmod.org:29418/CyanogenMod/android_device_samsung_espresso-common refs/changes/54/105854/1 && git cherry-pick FETCH_HEAD
git fetch ssh://Android-Andi@review.cyanogenmod.org:29418/CyanogenMod/android_device_samsung_espresso-common refs/changes/55/105855/1 && git cherry-pick FETCH_HEAD
git fetch ssh://Android-Andi@review.cyanogenmod.org:29418/CyanogenMod/android_device_samsung_espresso-common refs/changes/56/105856/1 && git cherry-pick FETCH_HEAD
git fetch ssh://Android-Andi@review.cyanogenmod.org:29418/CyanogenMod/android_device_samsung_espresso-common refs/changes/00/105900/1 && git cherry-pick FETCH_HEAD
git fetch ssh://Android-Andi@review.cyanogenmod.org:29418/CyanogenMod/android_device_samsung_espresso-common refs/changes/01/105901/1 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "DONE"
echo "----------------------------------------"
echo "----------------------------------------"
