#!/bin/bash
SAUCE=~/android/cm-11.0

# Let's apply all commits!
echo "----------------------------------------"
echo "----------------------------------------"

repopick -t cm11.0-appops-su
repopick -t bootzip-cm-11.0
repopick -t asb-2018.04-cm11

cd $SAUCE/pull
. patch.sh
