#!/bin/bash
# Your build source code directory path. In the example below the build source code directory path is in the "home" folder. If your source code directory is on an external HDD it should look like: //media/your PC username/the name of your storage device/path/to/your/source/code/folder
SAUCE=~/android/cm-13.0

# Let's apply all commits!
echo ""
echo "----------------------------------------"
#repopick -t asb-2018.10-cm13
cd $SAUCE/build
git fetch https://github.com/LineageOS/android_build refs/changes/94/234594/3 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd $SAUCE/packages/apps/Settings
git fetch https://github.com/LineageOS/android_packages_apps_Settings refs/changes/08/230408/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd $SAUCE/pull
. patch.sh
