#!/bin/bash
echo "Patching to compile PhilZ Touch from Source"
cd device/samsung/p3100
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_p3100 refs/changes/87/63387/1 && git cherry-pick FETCH_HEAD
cd ..
cd p3110
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_p3110 refs/changes/88/63388/1 && git cherry-pick FETCH_HEAD
cd ..
cd p5100
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_p5100 refs/changes/85/63385/1 && git cherry-pick FETCH_HEAD
cd ..
cd p5110
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_p5110 refs/changes/86/63386/1 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "DONE"
