#!/bin/bash
echo ""
echo "----------------------------------------"
echo "----------------------------------------"
cd bootable/recovery
git pull https://review.slimroms.eu/SlimRoms/bootable_recovery refs/changes/73/6573/1
echo "----------------------------------------"
echo "new Stock TWRP UI"
git fetch https://gerrit.omnirom.org/android_bootable_recovery refs/changes/28/12728/21 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
echo "Done!"
echo "----------------------------------------"
echo "----------------------------------------"
