#!/bin/bash
echo ""
echo "----------------------------------------"
echo "----------------------------------------"
cd bootable/recovery
echo "----------------------------------------"
echo "new Stock TWRP UI"
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/bootable_recovery refs/changes/32/7032/2 && git cherry-pick FETCH_HEAD
git fetch ssh://andi34@review.slimroms.eu:29418/SlimRoms/bootable_recovery refs/changes/33/7033/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
echo "Done!"
echo "----------------------------------------"
echo "----------------------------------------"
