#!/bin/bash
cd frameworks/native
echo "Revert [2/3] STE OMX Fix https://gerrit.omnirom.org/6834"
git reset --hard HEAD~1
echo "----------------------------------------"
echo "Revert native:Fix buffering on Samsung STE devices https://gerrit.omnirom.org/6827"
git reset --hard HEAD~1
cd ..
echo "----------------------------------------"
cd av
echo "Revert STE Multimedia Fix https://gerrit.omnirom.org/6828"
git reset --hard HEAD~1
cd ..
echo "----------------------------------------"
cd base
echo "Revert [1/3] STE OMX Fix https://gerrit.omnirom.org/6829"
git reset --hard HEAD~1
cd ../..
echo "----------------------------------------"
cd system/core
echo "Revert [3/3] STE OMX Fix https://gerrit.omnirom.org/6830"
git reset --hard HEAD~1
echo "----------------------------------------"
echo "Revert Fix shutdown/reboot bug https://gerrit.omnirom.org/6831"
git reset --hard HEAD~1
cd ../..
echo "----------------------------------------"
cd packages/services/Telephony
echo "Revert Reset the audio stream volume to fix low in-call volume bug https://gerrit.omnirom.org/6832"
git reset --hard HEAD~1
cd ../../..
echo "----------------------------------------"
cd build
echo "Revert build: Add STE target-specific config https://gerrit.omnirom.org/7753"
git reset --hard HEAD~1
cd ..
echo "----------------------------------------"
echo "DONE"
