#!/bin/bash
echo "----------------------------------------"
echo "Patching smdk4412-common"
cd system/vold
echo "vold: Honor mount options for ext4 mounts https://gerrit.slimroms.net/#/c/10318/"
git fetch https://gerrit.slimroms.net/SlimRoms/android_system_vold refs/changes/18/10318/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
echo"Add exfat/ntfs support for modules or static mode. https://gerrit.slimroms.net/#/c/6929/"
git fetch https://gerrit.slimroms.net/SlimRoms/android_system_vold refs/changes/29/6929/6 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "DONE"
