#!/bin/bash
echo "Patching frameworks base"
cd frameworks/base
echo "Base: Follow 4.4 UI https://gerrit.omnirom.org/4577"
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/77/4577/2 && git cherry-pick FETCH_HEAD
echo "Framework: Add Landscape layout for ECA https://gerrit.omnirom.org/6455"
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/55/6455/1 && git cherry-pick FETCH_HEAD
echo "Base: Floating window with multitasking https://gerrit.omnirom.org/6380"
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/80/6380/20 && git cherry-pick FETCH_HEAD
echo "[1/2] Base: implement App circle sidebar https://gerrit.omnirom.org/6378"
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/78/6378/17 && git cherry-pick FETCH_HEAD
echo "Base: App Circle sidebar (add support floating window) https://gerrit.omnirom.org/6515"
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/15/6515/9 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "Patching vold"
cd system/vold
echo "Add exfat/ntfs support for modules or static mode. https://gerrit.omnirom.org/6886"
git fetch https://gerrit.omnirom.org/android_system_vold refs/changes/86/6886/10 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "Patching OmniGears"
cd packages/apps/OmniGears
echo "[2/2] OmniGears: Implement App circle sidebar https://gerrit.omnirom.org/6379"
git fetch https://gerrit.omnirom.org/android_packages_apps_OmniGears refs/changes/79/6379/6 && git cherry-pick FETCH_HEAD
cd ..
echo "----------------------------------------"
echo "Patching OmniSwitch"
cd OmniSwitch
echo "OmniSwitch: Allow open app as floating window https://gerrit.omnirom.org/6661"
git fetch https://gerrit.omnirom.org/android_packages_apps_OmniSwitch refs/changes/61/6661/1 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "DONE"
