#!/bin/bash
echo ""
echo ""
cd device/samsung/espresso-common
echo "nothing for now..."
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p3100
echo "nothing for now..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p3110
echo "nothing for now..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p5100
echo "nothing for now..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd device/samsung/p5110
echo "----------------------------------------"
echo "nothing for now..."
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd kernel/samsung/espresso10
echo "nothing for now..."
# echo "enforcing time"
# git fetch https://gerrit.omnirom.org/android_kernel_samsung_espresso10 refs/changes/91/12091/1 && git cherry-pick FETCH_HEAD
# echo "Overclocking stuff"
# git fetch https://gerrit.omnirom.org/android_kernel_samsung_espresso10 refs/changes/16/11216/1 && git cherry-pick FETCH_HEAD
# git fetch https://gerrit.omnirom.org/android_kernel_samsung_espresso10 refs/changes/17/11217/1 && git cherry-pick FETCH_HEAD
# git fetch https://gerrit.omnirom.org/android_kernel_samsung_espresso10 refs/changes/18/11218/1 && git cherry-pick FETCH_HEAD
# git fetch https://gerrit.omnirom.org/android_kernel_samsung_espresso10 refs/changes/19/11219/1 && git cherry-pick FETCH_HEAD
# git fetch https://gerrit.omnirom.org/android_kernel_samsung_espresso10 refs/changes/20/11220/1 && git cherry-pick FETCH_HEAD
# git fetch https://gerrit.omnirom.org/android_kernel_samsung_espresso10 refs/changes/21/11221/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd hardware/samsung
echo "nothing for now..."
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
cd frameworks/native
echo "nothing for now..."
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
cd frameworks/base
echo "nothing for now..."
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
cd frameworks/av
echo "nothing for now..."
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
cd frameworks/opt/telephony
echo "nothing for now..."
cd ../../..
echo "----------------------------------------"
echo "----------------------------------------"
cd vendor/omni
echo "vendor: add date and time by default for HOMEMADE builds  https://gerrit.omnirom.org/#/c/11379/"
git fetch https://gerrit.omnirom.org/android_vendor_omni refs/changes/79/11379/6 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
echo ""
echo "Done!"
echo "----------------------------------------"
echo "----------------------------------------"
