#!/bin/bash
echo "----------------------------------------"
echo "Patching smdk4412-common"
cd frameworks/av
echo "camera: Add required symbols for Samsung camera HAL; For lt01wifi, lt013g and lt01lte (exynos4) https://gerrit.slimroms.net/6935"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/35/6935/2 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
cd external/skia
echo "Add required symbol for newer Samsung external display https://gerrit.slimroms.net/9560"
git fetch https://gerrit.slimroms.net/SlimRoms/android_external_skia refs/changes/60/9560/1 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "DONE"
