#!/bin/bash
echo "Patching smdk4412-common"
cd device/samsung/smdk4412-common
echo "smdk4412-common: Add support for Tab 3 8.0"
git fetch https://gerrit.omnirom.org/android_device_samsung_smdk4412-common refs/changes/37/6437/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
echo -n "smdk4412-common: Don't build torch for devices without flash"
git fetch https://gerrit.omnirom.org/android_device_samsung_smdk4412-common refs/changes/38/6438/4 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
cd frameworks/av
echo "camera: Add required symbols for Samsung camera HAL; For lt01wifi, lt013g and lt01lte (exynos4) https://gerrit.slimroms.net/6935"
git fetch https://gerrit.slimroms.net/SlimRoms/frameworks_av refs/changes/35/6935/2 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
cd external/skia
echo "Add required symbol for newer Samsung external display https://gerrit.slimroms.net/9560"
git fetch https://gerrit.slimroms.net/SlimRoms/android_external_skia refs/changes/60/9560/1 && git cherry-pick FETCH_HEAD
cd ../..
echo "DONE"
