#!/bin/bash
echo "----------------------------------------"
cd frameworks/base
echo "Base: Follow 4.4 UI https://gerrit.omnirom.org/4577"
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/77/4577/4 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
cd packages/apps/Camera2
echo "camera2: follow 4.4 UI guidelines https://gerrit.omnirom.org/7752"
git fetch https://gerrit.omnirom.org/android_packages_apps_Camera2 refs/changes/52/7752/1 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"