#!/bin/bash
echo "----------------------------------------"
echo "----------------------------------------"
echo " V O L U M E   M U S I C   C O N T R O L "
echo ""
echo "https://review.slimroms.eu/#/q/topic:volume-music-control"
echo "----------------------------------------"
echo "----------------------------------------"
cd packages/apps/Settings
git fetch https://review.slimroms.eu/SlimRoms/packages_apps_Settings refs/changes/06/5406/2 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../../..
echo "----------------------------------------"
cd frameworks/base
git fetch https://review.slimroms.eu/SlimRoms/frameworks_base refs/changes/03/5403/3 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/frameworks_base refs/changes/04/5404/3 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
git fetch https://review.slimroms.eu/SlimRoms/frameworks_base refs/changes/05/5405/3 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
cd ../..
echo "----------------------------------------"
echo "----------------------------------------"
echo "DONE"
echo "----------------------------------------"
