#!/bin/bash
# Your build source code directory path. In the example below the build source code directory path is in the "home" folder. If your source code directory is on an external HDD it should look like: //media/your PC username/the name of your storage device/path/to/your/source/code/folder
SAUCE=~/android/cm-13.0

# Let's apply all commits!
echo ""
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/device/samsung/espresso
echo "----------------------------------------"
echo "sensor debugging"
git fetch http://review.cyanogenmod.org/CyanogenMod/android_device_samsung_espresso-common refs/changes/96/133896/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/device/samsung/espresso3g
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/kernel/samsung/espresso10
echo "----------------------------------------"
echo "----------------------------------------"
cd $SAUCE/vendor/samsung
echo "----------------------------------------"
git fetch https://github.com/andi34/proprietary_vendor_samsung-1.git cm-13.0
git cherry-pick d55e473a1b232deec5d0daeadf5b4856051c1449
echo "----------------------------------------"
echo "----------------------------------------"
echo "Done!"
cd $SAUCE
echo "----------------------------------------"
echo "----------------------------------------"
